#!/bin/bash

g++ -O3 -std=c++11 -o simCC.out simCC.cpp -lgsl -lgslcblas -lm -larmadillo
g++ -O3 -std=c++11 -o simCC_full.out simCC_full.cpp -lgsl -lgslcblas -lm -larmadillo

## for armadillo library compile with:
# -larmadillo

## armadillo needs at least c++11 in order to work, thus add:
# -std=c++11

## in order to link gsl, add:
# -lgsl -lgslcblas -lm
